### ISSUE TITLE
invalid input defined or SSL error: 'module' object has no attribute 'PROTOCOL_TLSv1_2'

### ISSUE THREAD

**Issue by irshad9998** [GerbenJavado/LinkFinder#42]
Hey,

I got this error  `invalid input defined or SSL error: 'module' object has no attribute 'PROTOCOL_TLSv1_2'`.

`root@localhost:~/Documents/LinkFinder# python linkfinder.py -i https://example.com -d
Usage: python linkfinder.py [Options] use -h for help
Error: invalid input defined or SSL error: 'module' object has no attribute 'PROTOCOL_TLSv1_2'
`
Regards

**Comment by GerbenJavado** [comment]
@irshad9998 Thanks for reporting! I'll look into it.

**Comment by Bankde** [comment]
I have noticed we're using low level urllib. Should we use python Requests instead ?
Requests lib might handle that for us.

**Comment by gh0stkey** [comment]
Hey,man.I think i have the same problem as you,but i fixed it.
You can change the code of `linkfinder.py`.
Original Code:
```python
sslcontext = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)

...code

response = urlopen(q, context=sslcontext)
```
After the change of code:
```python
# Support websites that force TLSv1.2

...code

try:
    sslcontext = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
    response = urlopen(q, context=sslcontext)
except:
    sslcontext = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
    response = urlopen(q, context=sslcontext)
```

**Comment by GerbenJavado** [comment]
I swapped out requests originally because it gave very bad performance. (some problems with using it for very large textfiles in combination with file://)

**Comment by GerbenJavado** [comment]
@gh0stkey Thank you so much for the suggestion. Ill try it out and add it to LinkFinder.

**Comment by pcastagnaro** [comment]
Hi guys,

I am getting a similar error: `urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:727)`. How can I repair it?

Thanks!

**Comment by ysl4life** [comment]
also having the same issue still, even with the new version with the fix from @gh0stkey

**Comment by Syazvinski** [comment]
still having the issue here

**Comment by Bankde** [comment]
@Syazvinski Can we have the error message, and (if you could) step to reproduce and the website you're testing?

**Comment by doverman22** [comment]
Hi there, I'm having the following errors when launching against a target:
```sh
/opt/LinkFinder/linkfinder.py:133: DeprecationWarning: ssl.PROTOCOL_TLSv1_2 is deprecated
  sslcontext = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
```

**Comment by doverman22** [comment]
Hi there, when launching against a target I'm having the following error:
```
/opt/LinkFinder/linkfinder.py:133: DeprecationWarning: ssl.PROTOCOL_TLSv1_2 is deprecated
  sslcontext = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
                                                                                                                                                                                                          
libEGL warning: DRI2: failed to authenticate
```

**Comment by ghost-man01** [comment]
Hey I'm getting the same issue of `sslcontext`.
